import React, {useEffect, useLayoutEffect, useRef, useState} from "react";
import Lenis from "lenis";
import {gsap} from "gsap";
import {ScrollTrigger} from "gsap/ScrollTrigger";
import {ArrowDownRight, ArrowUpRight, Code2, Cpu, Download, Menu, MoveRight, X} from "lucide-react";
import {usePage} from "../../contexts/PageContext";

gsap.registerPlugin(ScrollTrigger);

const resumeUrl = require("../../assets/cv/fatmabenmloukacv.pdf");

const missions = [
  {name: "FoundersLab", type: "Intelligent startup incubation platform", brief: "An online incubator that connects founders with investors, mentors, and the resources to grow — from idea to funded momentum.", challenge: "Founders arrive with ambition but no clear path, while investors struggle to surface promising early-stage signals.", solution: "Designed a SaaS platform where founders build a profile, get scored by a machine-learning model, and are matched with relevant investors and mentors — deployed on a personal OpenStack and Kubernetes cloud with CI/CD and observability.", stack: ["Angular", "Spring Boot", "MySQL", "ML scoring"], lesson: "The best tools reduce uncertainty, not just clicks.", accent: "rose", demo: "https://lnkd.in/p/eUiWEGzm"},
  {name: "StackPilot", type: "Cloud infrastructure & DevOps", brief: "A private cloud built to host production platforms — provisioned, automated, and monitored end to end.", challenge: "Turning scattered cloud resources into a repeatable, dependable platform for hosting real products.", solution: "Provisioned a private OpenStack cloud, codified infrastructure with Ansible and Terraform, orchestrated services on Kubernetes, and shipped it all through CI/CD with Prometheus and Grafana observability.", stack: ["OpenStack", "Ansible", "Terraform", "Kubernetes"], lesson: "Good infrastructure design is empathetic design.", accent: "blue"},
  {name: "AutoMatch", type: "Applied AI", brief: "A real-time car valuation system that turns vehicle data into confident pricing decisions.", challenge: "Car pricing is noisy and opaque — predictions must be accurate without feeling like a black box.", solution: "Built regression, classification, and clustering models served through a Flask API, with a Next.js frontend for transparent, interactive predictions and deployment on Vercel.", stack: ["Flask", "Next.js", "Regression", "Clustering"], lesson: "AI earns trust through clarity and context.", accent: "lime"},
  {name: "AI Psychometric Assessment Platform", type: "Intelligence systems", brief: "An AI-powered psychometric assessment platform that turns raw responses into clear, human feedback.", challenge: "Assessment data is rich but noisy — feedback had to be nuanced, transparent, and genuinely useful.", solution: "Built automated analysis pipelines and AI modules over a Django backend, producing guided assessments and AI-assisted profile reports people can actually act on.", stack: ["Django", "Python", "AI pipelines"], lesson: "Sensitive systems need calm, transparent interfaces.", accent: "violet"},
  {name: "FITSYNC", type: "Sports management platform", brief: "A sports management platform that keeps tournaments, teams, and athletes in sync without the overhead.", challenge: "Managing tournaments, teams, and athlete performance across scattered tools creates friction and errors.", solution: "Implemented tournament, team, and athlete performance modules with modern, interactive JavaFX interfaces, backed by a Symfony web layer and MySQL.", stack: ["Java", "Symfony", "JavaFX", "MySQL"], lesson: "The smallest encouraging moments can sustain a habit.", accent: "orange"},
  {name: "FYP Cooked", type: "AI browser extension", brief: "Your FYP, explained. A private AI analysis of the reels you actually watch — no guesses, just the algorithm's receipts.", challenge: "Your feed shapes your attention in real time, but the algorithm's effect on you stays invisible while you scroll.", solution: "Built a browser extension that analyzes each Instagram Reel silently with on-device AI, then turns your viewing into a live Brainrot Index, a weekly story-like Wrapped, and personalized recommendations — all locally, with zero data leaving your device.", stack: ["Browser extension", "On-device AI", "Local-first", "JavaScript"], lesson: "Clarity about how a system shapes you is the first form of control.", accent: "amber", demo: "https://github.com/fatma2708/fyp-analyzer"}
];

const repositories = [
  {name: "FoundersLab", url: "https://github.com/AdamLamine0/project-pi", stack: "Angular · Spring Boot · MySQL", description: "An online startup incubation platform that connects founders with investors and mentors, with ML-based startup scoring."},
  {name: "AutoMatchAI", url: "https://github.com/fatma2708/AutoMatchAI", stack: "Next.js · React Native · Flask · ML", description: "A used-car intelligence platform with web, mobile, and ML services for prediction and scoring."},
  {name: "psychology-assessement", url: "https://github.com/fatma2708/psychology-assessement", stack: "Django · Python · PostgreSQL", description: "A multilingual psychology assessment app with guided flows and AI-assisted profile reports."},
  {name: "sportsmanagementapp", url: "https://github.com/fatma2708/sportsmanagementapp", stack: "Java", description: "A Java starter project laid out for future sports management features and expansion."},
  {name: "sportsmanagementweb", url: "https://github.com/fatma2708/sportsmanagementweb", stack: "Symfony · PHP · MySQL", description: "A Symfony web app for project and user management with authentication and messaging tools."},
  {name: "Hotel Management", url: "https://github.com/fatma2708/ProjetPHP_Hotel_management", stack: "PHP", description: "A PHP hotel management project documenting workflow scope and hospitality features."},
  {name: "Gameland", url: "https://github.com/fatma2708/Gameland", stack: "Python · Django · HTML", description: "A Django project combining user flows, agency data, and a lightweight interactive game."},
  {name: "InnOpti", url: "https://github.com/fatma2708/InnOpti", stack: "React Native · JavaScript", description: "A React Native prototype for profile setup, navigation, and habit-tracking interactions."},
  {name: "FYP Cooked", url: "https://github.com/fatma2708/fyp-analyzer", stack: "Browser extension · On-device AI", description: "A private, local-first AI browser extension that analyzes your Instagram Reels and reveals exactly what your feed is doing to you."}
];

const skillThemes = [
  {name: "Cloud & DevOps", skills: ["Docker", "Kubernetes", "OpenStack", "Terraform", "Ansible", "CI/CD", "Linux"], note: "Containerized, automated infrastructure that stays calm under load.", where: "StackPilot · FoundersLab"},
  {name: "Frontend", skills: ["Angular", "Next.js", "React", "JavaFX", "HTML", "CSS", "Bootstrap"], note: "Interfaces that turn complex systems into clear, human experiences.", where: "FoundersLab · AutoMatch · FITSYNC"},
  {name: "Backend", skills: ["Spring Boot", "Django", "Flask", "Node.js", "REST APIs"], note: "Services and APIs engineered to scale without drama.", where: "FoundersLab · AutoMatch · Assessment"},
  {name: "Machine Learning", skills: ["Regression", "Clustering", "Decision Trees", "Pandas", "NumPy"], note: "Models that help people make better, more confident decisions.", where: "AutoMatch · Psychometric Assessment"},
  {name: "Languages", skills: ["Python", "Java", "JavaScript", "PHP", "C#", "C", "C++"], note: "Broad, deep foundations across paradigms and platforms.", where: "The substrate behind every mission"}
];

const certificates = [
  {title: "AI Fundamentals with IBM SkillsBuild", issuer: "Cisco", image: "https://images.credly.com/images/26c21273-c0ab-485b-98a7-f1212dcb82b8/linkedin_thumb_image.png", link: "https://www.credly.com/badges/03a7b076-df8e-49cf-bf7d-b0af9fff538e"},
  {title: "Artificial Intelligence Fundamentals", issuer: "IBM SkillsBuild", image: "https://images.credly.com/images/82b908e1-fdcd-4785-9d32-97f11ccbcf08/linkedin_thumb_image.png", link: "https://www.credly.com/badges/b320bbb6-60ea-4938-85f3-9df2735ff534"},
  {title: "AWS Knowledge: Cloud Essentials", issuer: "Amazon Web Services", image: "https://images.credly.com/images/7cf036b0-c609-4378-a7be-9969e1dea7ab/linkedin_thumb_blob", link: "https://www.credly.com/badges/949dd529-7d52-4e9e-9d79-aa84463c1cd1"},
  {title: "CCNA: Switching, Routing, and Wireless Essentials", issuer: "Cisco", image: "https://images.credly.com/images/f4ccdba9-dd65-4349-baad-8f05df116443/linkedin_thumb_CCNASRWE__1_.png", link: "https://www.credly.com/badges/42694d0e-2c13-46ca-937c-37f288a76bbe"},
  {title: "Python Essentials 2", issuer: "Cisco", image: "https://images.credly.com/images/3f802526-7274-4230-91ab-f6d1a35340e6/linkedin_thumb_image.png", link: "https://www.credly.com/badges/5203286b-6a69-422e-a610-f76d705e8299"},
  {title: "Understanding Machine Learning", issuer: "DataCamp", monogram: "ML", link: "https://www.datacamp.com/statement-of-accomplishment/course/ceeb34b6336721c6281663bb9411c913d2921b4a"},
  {title: "Understanding Data Science", issuer: "DataCamp", monogram: "DS", link: "https://www.datacamp.com/statement-of-accomplishment/course/df26c9cd370e05a4ccaaa850762e44e14c257248"},
  {title: "CCNA: Introduction to Networks", issuer: "Cisco Networking Academy", monogram: "ITN", link: "https://www.netacad.com/certificates?issuanceId=2b6e22d5-70e8-4fa4-8203-e781a5aa1f45"},
  {title: "Principles of UX/UI Design", issuer: "Meta · Coursera", monogram: "UX", link: "https://coursera.org/share/5043460adc119d07c3da2e87f97a477a"},
  {title: "Evaluation and Light Customization of Large Language Models", issuer: "NVIDIA", monogram: "NV", link: "https://learn.nvidia.com/certificates?id=FILHuqksSYeRatJJpBaYDQ"}
];

function useReducedMotion() {
  const [reduced, setReduced] = useState(false);
  useEffect(() => { const media = window.matchMedia("(prefers-reduced-motion: reduce)"); const listener = () => setReduced(media.matches); listener(); media.addListener(listener); return () => media.removeListener(listener); }, []);
  return reduced;
}

function SectionTitle({kicker, title, copy}) { return <header className="section-title"><span>{kicker}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</header>; }

function BootSequence({onDone, reduced}) {
  const root = useRef(null);
  useLayoutEffect(() => { const ctx = gsap.context(() => { const timeline = gsap.timeline({onComplete: onDone}); timeline.to(".boot-line", {opacity: 1, stagger: .25, duration: .2}).to(".boot-progress span", {width: "100%", duration: reduced ? .2 : 1.5, ease: "power2.inOut"}).to(root.current, {opacity: 0, duration: .45, delay: .25, pointerEvents: "none"}); }, root); return () => ctx.revert(); }, [onDone, reduced]);
  return <div className="boot" ref={root} aria-live="polite"><div className="boot-shell"><p className="boot-label">FATMA PORTFOLIO / STARTUP SEQUENCE</p>{["Loading AI Engine...", "Loading Cloud Stack...", "Loading Interface Lab...", "Loading Creativity Module...", "Boot complete."].map((line, index) => <p className="boot-line" key={line}><b>0{index + 1}</b>{line}</p>)}<div className="boot-progress"><span /></div><small>ESTABLISHING A BETTER KIND OF SYSTEM</small></div></div>;
}

function Navigation({open, setOpen}) { const links = [["identity", "Identity"], ["missions", "Missions"], ["skills", "Capabilities"], ["journey", "Journey"], ["certificates", "Certificates"], ["contact", "Contact"]]; return <><header className="topbar"><a href="#identity" className="wordmark" aria-label="Fatma portfolio home">FATMA<span>Folio</span></a><nav className={open ? "nav-links open" : "nav-links"} aria-label="Main navigation">{links.map(([id, label]) => <a key={id} href={`#${id}`} onClick={() => setOpen(false)}>{label}</a>)}</nav><button className="menu-button" onClick={() => setOpen(!open)} aria-label="Toggle menu">{open ? <X /> : <Menu />}</button></header></>; }

function Hero() { return <section className="hero" id="identity"><div className="hero-copy"><p className="eyebrow">FATMA BEN MLOUKA <i /> CLOUD COMPUTING ENGINEERING</p><h1><span>Ideas that</span><em>think, scale,</em><span>and feel right.</span></h1><p className="hero-summary">Cloud Computing student and engineer building thoughtful systems at the intersection of AI, scalable infrastructure, and experience.</p><a className="round-link" href="#missions">Enter the system <ArrowDownRight /></a></div><div className="hero-orbit" aria-hidden="true"><div className="orbit orbit-a" /><div className="orbit orbit-b" /><div className="core"><Cpu /></div><span>AI</span><span>Cloud</span><span>Design</span></div><div className="scroll-cue">SCROLL TO EXPLORE <span /></div></section>; }

function MissionArchive() { const {setProject} = usePage(); const [selected, setSelected] = useState(null); return <section id="missions" className="mission-archive"><SectionTitle kicker="01 / MISSION ARCHIVE" title="Work with a pulse." copy="Six product stories where technical ambition and visual intention meet." /><div className="mission-grid">{missions.map((mission, index) => <article key={mission.name} className={`mission-card ${mission.accent}`} onMouseMove={event => { const card = event.currentTarget; const rect = card.getBoundingClientRect(); card.style.setProperty("--rotate-x", `${(rect.height / 2 - (event.clientY - rect.top)) / 18}deg`); card.style.setProperty("--rotate-y", `${((event.clientX - rect.left) - rect.width / 2) / 18}deg`); }} onMouseLeave={event => event.currentTarget.removeAttribute("style")}><div className="mission-card-head"><span>MISSION / 0{index + 1}</span><button onClick={() => { const next = selected === index ? null : index; setSelected(next); setProject(next === null ? "" : missions[next].name); }} aria-expanded={selected === index} aria-label={`Open ${mission.name} case study`}><ArrowUpRight /></button></div><p>{mission.type}</p><h3>{mission.name}</h3><div className="mission-visual"><span /><span /><span /></div><p className="mission-brief">{mission.brief}</p>{selected === index && <div className="mission-detail"><p><b>Challenge</b>{mission.challenge}</p><p><b>Solution</b>{mission.solution}</p><p><b>Stack</b>{mission.stack.join(" · ")}</p><p><b>Lesson</b>{mission.lesson}</p><div className="case-links">{mission.demo && <a href={mission.demo} target="_blank" rel="noreferrer">Watch demo <ArrowUpRight /></a>}</div></div>}</article>)}</div><div className="repository-index"><p>REPOSITORY INDEX / VERIFIED SOURCES</p><div>{repositories.map(repository => <article key={repository.url} className="repository-card"><div><span>{repository.stack}</span><h3>{repository.name}</h3><p>{repository.description}</p></div><a href={repository.url} target="_blank" rel="noreferrer" aria-label={`View ${repository.name} on GitHub`}>View source <ArrowUpRight /></a></article>)}</div></div></section>; }

function SkillsConstellation() { const [current, setCurrent] = useState(0); return <section id="skills" className="constellation"><SectionTitle kicker="02 / CAPABILITY MAP" title="A constellation, not a checklist." copy="Hover a node to see the full skill set behind each theme." /><div className="constellation-board"><div className="skill-nodes">{skillThemes.map((theme, index) => <button key={theme.name} className={current === index ? "skill-node active" : "skill-node"} onMouseEnter={() => setCurrent(index)} onFocus={() => setCurrent(index)} onClick={() => setCurrent(index)} style={{"--x": `${[12, 46, 80, 71, 24][index]}%`, "--y": `${[24, 12, 34, 73, 77][index]}%`}}>{theme.name}</button>)}</div><div className="skill-story"><span>NODE / 0{current + 1}</span><h3>{skillThemes[current].name}</h3><p>{skillThemes[current].note}</p><div className="skill-chips">{skillThemes[current].skills.map(skill => <span key={skill}>{skill}</span>)}</div><small>{skillThemes[current].where}</small></div></div></section>; }

function Timeline() { return <section className="timeline" id="journey"><SectionTitle kicker="03 / JOURNEY LOG" title="The path stays in motion." copy="A record of engineering foundations, internships, leadership, and continued curiosity." /><div className="timeline-line">{[["2022—Present", "ESPRIT Engineering", "Computer Engineering degree specialized in Cloud Computing, with a focus on AI, cloud-native, and full-stack development."], ["07/2025 — 08/2025", "Intech Solutions · AI Intern", "Built an AI-based psychometric assessment platform with automated analysis pipelines and integrated AI modules."], ["08/2023 — 09/2023", "Intech Solutions · Web Dev Intern", "Developed backend features using Django."], ["2023 — 2024", "IEEE RAS ESPRIT SBC", "Media Manager — grew event visibility and covered workshops, competitions, and conferences."]].map(([date, title, desc]) => <article key={title}><span>{date}</span><i /><div><h3>{title}</h3><p>{desc}</p></div></article>)}</div><div className="polaroids">{["A cloud engineer who believes infrastructure is a design problem.", "Always curious about the person on the other side of the interface.", "Believes engineering and design are one conversation."].map((fact, index) => <div className="polaroid" key={fact} style={{"--tilt": `${[-3, 3, -2][index]}deg`}}><div>FBM</div><p>{fact}</p><small>FIELD NOTE / 0{index + 1}</small></div>)}</div></section>; }

function CertificateHand() { const N = certificates.length; return <section id="certificates" className="certificates"><SectionTitle kicker="04 / BADGE COLLECTION" title="A hand worth holding." copy="Cloud, AI, networking, and design credentials — earned, verified, and stacked." /><div className="certificate-fan">{certificates.map((cert, index) => <article key={cert.title} className="certificate-card" style={{"--angle": `${((index - (N - 1) / 2) * 10).toFixed(1)}deg`}}><div className="certificate-face">{cert.image ? <img src={cert.image} alt={`${cert.title} badge`} loading="lazy" /> : <div className="certificate-monogram">{cert.monogram}</div>}<span className="certificate-issuer">{cert.issuer}</span><h3>{cert.title}</h3></div><a href={cert.link} target="_blank" rel="noreferrer">Verify <ArrowUpRight /></a></article>)}</div></section>; }

function ContactTerminal() { const [open, setOpen] = useState(false); const [email, setEmail] = useState(""); const [message, setMessage] = useState(""); const submit = (e) => { e.preventDefault(); window.location.href = `mailto:fatmabenmlouka38@gmail.com?subject=${encodeURIComponent("Portfolio — new conversation request")}&body=${encodeURIComponent(`From: ${email}\n\n${message}`)}`; }; return <section id="contact" className="contact-terminal"><p className="eyebrow">05 / OPEN CHANNEL</p><h2>Let’s build<br /><em>something with signal.</em></h2><p>Have an idea, opportunity, or a difficult system worth making better?</p><div className={open ? "terminal-window open" : "terminal-window"}><span>fatma@folio:~$</span>{open ? <form className="terminal-form" onSubmit={submit}><input type="email" placeholder="your_email" value={email} onChange={e => setEmail(e.target.value)} required /><textarea rows={3} placeholder="message..." value={message} onChange={e => setMessage(e.target.value)} required /><button type="submit">send_signal <ArrowUpRight /></button></form> : <button className="terminal-command" onClick={() => setOpen(true)}>initiate_conversation <ArrowUpRight /></button>}</div><div className="contact-actions"><a href={resumeUrl} download="Fatma_Ben_Mlouka_CV.pdf"><Download /> Download CV</a><a href="https://github.com/fatma2708" target="_blank" rel="noreferrer"><Code2 /> GitHub</a><a href="https://www.linkedin.com/in/fatma-ben-mlouka-229a0b213/?locale=fr" target="_blank" rel="noreferrer"><MoveRight /> LinkedIn</a></div></section>; }

export default function FatmaOS() {
  const reduced = useReducedMotion(); const [booted, setBooted] = useState(false); const [menuOpen, setMenuOpen] = useState(false); const content = useRef(null);
  useEffect(() => { console.log("Fatma portfolio online — welcome, curious human."); }, []);
  useEffect(() => { if (reduced || !booted) return; const lenis = new Lenis({lerp: .09, smoothWheel: true}); let frame; const raf = time => {lenis.raf(time); frame = requestAnimationFrame(raf);}; frame = requestAnimationFrame(raf); return () => {cancelAnimationFrame(frame); lenis.destroy();}; }, [booted, reduced]);
  useLayoutEffect(() => { if (!booted || reduced) return; const ctx = gsap.context(() => { gsap.from(".hero-copy > *, .hero-orbit", {y: 28, opacity: 0, stagger: .12, duration: .9, ease: "power3.out"}); gsap.utils.toArray(".section-title, .mission-card, .timeline article, .certificate-card").forEach(element => gsap.from(element, {scrollTrigger: {trigger: element, start: "top 84%", once: true}, y: 30, opacity: 0, duration: .7, ease: "power2.out"})); }, content); return () => ctx.revert(); }, [booted, reduced]);
  return <div className={reduced ? "fatma-os reduced" : "fatma-os"}>{!booted && <BootSequence reduced={reduced} onDone={() => setBooted(true)} />}{booted && <><Navigation open={menuOpen} setOpen={setMenuOpen} /><main ref={content}><Hero /><div className="story-flow" aria-live="polite"><MissionArchive /><SkillsConstellation /><Timeline /><CertificateHand /><ContactTerminal /></div></main><footer>FATMA PORTFOLIO <span>© {new Date().getFullYear()} / BUILT WITH INTENTION</span><a href="#identity">Back to top ↑</a></footer></>}</div>;
}
